stages:
  - prebuild
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

services:
    - docker:19.03.1-dind
  
variables:
  #DOCKER_HOST: tcp://docker:2376
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

version_extractor:
  stage: prebuild
  image:
    name: realguess/jq
  services: []
  tags:
    - shared
  artifacts:
    paths:
      - web-api-version.txt
    expire_in: 1 week
  script:
    - jq -r '.version' package.json > web-api-version.txt

build:docker:
  stage: build
  image: docker:git
  tags:
    - docker
  dependencies:
    - version_extractor
  script:
    - mkdir -p sensitive
    - echo ${PRV_KEY} > sensitive/key
    - echo ${PUB_KEY} > sensitive/key.pub
    - echo ${KEY_PASS} > sensitive/pass
    - SEET_API_VERSION=$(cat web-api-version.txt)
    - DOCKER_IMAGE_TEST_VERSION_TAG=${CI_REGISTRY_IMAGE}/webapi:${SEET_API_VERSION}-TEST
    - docker build -t ${DOCKER_IMAGE_TEST_VERSION_TAG} .
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker push ${DOCKER_IMAGE_TEST_VERSION_TAG}

test:api:
  stage: test
  image: docker:git
  tags:
    - docker
  dependencies:
    - version_extractor
  artifacts:
    when: always
    reports:
      junit: ci/report.xml
    expire_in: 30 days
  services:
    - postgres:latest
    - docker:19.03.1-dind
  variables:
    POSTGRES_USER: seet_tester
    POSTGRES_PASSWORD: POKEMON
    POSTGRES_DB: seet
    API_USER: seet_tester
    API_USER_EMAIL: seet_tester@seet.com
    API_USER_ROLE: admin
    API_USER_PASSWORD: DIGIMON 
  script:
    - SEET_API_VERSION=$(cat web-api-version.txt)
    - DOCKER_IMAGE_TEST_VERSION_TAG=${CI_REGISTRY_IMAGE}/webapi:${SEET_API_VERSION}-TEST
    - echo ${DOCKER_IMAGE_TEST_VERSION_TAG}
    # Initiating the database
    # Generating the user password hash to store using the app image to avoid performing an unecessary 'npm ci'
    - >
      docker run \
        --rm \
        -e API_USER_PASSWORD=${API_USER_PASSWORD} \
        ${DOCKER_IMAGE_TEST_VERSION_TAG} \
        node --experimental-modules ci/user-passwd-crypt.mjs ${API_USER_PASSWORD} > hashed-password.txt
    - echo >>ci/initdb.sql 'INSERT INTO public.users VALUES ('"'"${API_USER}"'"', '"'"${API_USER_EMAIL}"'"', '"'"$(cat hashed-password.txt)"'"', '"'"${API_USER_ROLE}"'"');'
    - >
      docker run \
        --rm \
        --add-host postgres:${POSTGRES_PORT_5432_TCP_ADDR} \
        -e PGHOST="postgres" \
        -e PGUSER=${POSTGRES_USER} \
        -e PGPASSWORD=${POSTGRES_PASSWORD} \
        -e PGDATABASE=${POSTGRES_DB} \
        -v ${CI_PROJECT_DIR}/ci/initdb.sql:/initdb.sql \
        postgres \
        psql -f /initdb.sql
    # Running the API test container
    - >
      docker run \
        --name seet_web_api \
        --add-host postgres:${POSTGRES_PORT_5432_TCP_ADDR} \
        --net host \
        -p 8000:8000 \
        -e SEET_API_PORT=8000 \
        -e SEET_API_VERSION=${SET_API_VERSION} \
        -e PGHOST="postgres" \
        -e PGUSER=${POSTGRES_USER} \
        -e PGPASSWORD=${POSTGRES_PASSWORD} \
        -e PGDATABASE=${POSTGRES_DB} \
        -d ${DOCKER_IMAGE_TEST_VERSION_TAG}
    # Running Postman tests
    - wget -O ci/postman_collection.json https://www.getpostman.com/collections/96a843d50e3a3623926c
    - >
      docker run \
        -v ${CI_PROJECT_DIR}/ci:/ci \
        --rm \
        --net host \
        postman/newman \
        run /ci/postman_collection.json --reporters cli,junit --reporter-junit-export /ci/report.xml

deploy:docker:
  stage: deploy
  image: docker:git
  tags:
    - docker
  dependencies:
    - version_extractor
  script:
    - SEET_API_VERSION=$(cat web-api-version.txt)
    - DOCKER_IMAGE_VERSION_TAG=${CI_REGISTRY_IMAGE}/webapi:${SEET_API_VERSION}
    - DOCKER_IMAGE_TEST_VERSION_TAG=${DOCKER_IMAGE_VERSION_TAG}-TEST
    - docker tag ${DOCKER_IMAGE_TEST_VERSION_TAG} ${DOCKER_IMAGE_VERSION_TAG}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${DOCKER_IMAGE_VERSION_TAG}
